package sg.edu.nus.iss.wellness.model;

import jakarta.persistence.*;

import java.time.Instant;

/**
 * Saved recommendation generated by the Python agent.
 *
 * @author Tiong Zhong Cheng
 */
@Entity
@Table(name = "recommendations", indexes = @Index(name = "idx_recommendations_user_created", columnList = "user_id,created_at"))
public class Recommendation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private AppUser user;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false, columnDefinition = "TEXT", name = "trend_summary")
    private String trendSummary;

    @Column(nullable = false, columnDefinition = "TEXT", name = "recommendation_text")
    private String recommendationText;

    @Column(columnDefinition = "TEXT", name = "action_items")
    private String actionItems;

    @Column(nullable = false, name = "generated_by")
    private String generatedBy = "python-agent";

    @Column(nullable = false, name = "created_at")
    private Instant createdAt = Instant.now();

    public Long getId() { return id; }
    public AppUser getUser() { return user; }
    public void setUser(AppUser user) { this.user = user; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getTrendSummary() { return trendSummary; }
    public void setTrendSummary(String trendSummary) { this.trendSummary = trendSummary; }
    public String getRecommendationText() { return recommendationText; }
    public void setRecommendationText(String recommendationText) { this.recommendationText = recommendationText; }
    public String getActionItems() { return actionItems; }
    public void setActionItems(String actionItems) { this.actionItems = actionItems; }
    public String getGeneratedBy() { return generatedBy; }
    public void setGeneratedBy(String generatedBy) { this.generatedBy = generatedBy; }
    public Instant getCreatedAt() { return createdAt; }
}
