sonar.projectKey=sa62-wellness-python-ai
sonar.projectName=SA62 Wellness Python AI Service
sonar.projectBaseDir=.
sonar.sources=app
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/.venv/**,**/venv/**
