sonar.projectKey=sa62-wellness-android
sonar.projectName=SA62 Wellness Android
sonar.projectBaseDir=.
sonar.sources=app/src/main/java,app/src/main/res,app/src/main/AndroidManifest.xml
sonar.tests=app/src/test
sonar.java.binaries=app/build/tmp/kotlin-classes/debug
sonar.androidLint.reportPaths=app/build/reports/lint-results-debug.xml
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/coverage/test/debug/report.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/build/**,**/.gradle/**,**/gradle/wrapper/**
